version: '3.2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "9443:443"
      - "9080:80"
      - "9022:22"
    volumes:
      - ./config:/etc/gitlab:rw
      - ./logs:/var/log/gitlab:rw
      - ./data:/var/opt/gitlab:rw
    restart: always
